### PR TITLE
Some HTTPS fixes and docs

### PR DESCRIPTION
**Pull request by complynx**

### CODE REVIEW

**Comment by mlassnig** [comment]
Hi,

this fails both on py26 and py27:

$ ./pilot.py -d -q DESY-HH_TEST -l 300
2017-04-20 15:53:52,573 | INFO     | MainThread | __main__                         | main                             | pilot startup - version 2017-04-04.001
2017-04-20 15:53:52,576 | DEBUG    | MainThread | pilot.util.https                 | https_setup                      | User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)
Traceback (most recent call last):
  File "./pilot.py", line 104, in <module>
    trace = main()
  File "./pilot.py", line 29, in main
    if not https_setup(args, VERSION):
  File "/data/pilot2/pilot2/pilot2/pilot/util/https.py", line 114, in https_setup
    _ctx.capath = capath(args)
  File "/data/pilot2/pilot2/pilot2/pilot/util/https.py", line 60, in capath
    '/etc/grid-security/certificates')
  File "/data/pilot2/pilot2/pilot2/pilot/util/https.py", line 37, in _tester
    if func(arg):
  File "/usr/lib64/python2.6/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found


$ ./pilot.py -d -q DESY-HH_TEST -l 300
2017-04-20 15:49:49,375 | INFO     | MainThread | __main__                         | main                             | pilot startup - version 2017-04-04.001
2017-04-20 15:49:49,382 | DEBUG    | MainThread | pilot.util.https                 | https_setup                      | User-Agent: pilot/2017-04-04.001 (Python 2.7.9; Linux x86_64)
Traceback (most recent call last):
  File "./pilot.py", line 104, in <module>
    trace = main()
  File "./pilot.py", line 29, in main
    if not https_setup(args, VERSION):
  File "/data/pilot2/pilot/util/https.py", line 114, in https_setup
    _ctx.capath = capath(args)
  File "/data/pilot2/pilot/util/https.py", line 60, in capath
    '/etc/grid-security/certificates')
  File "/data/pilot2/pilot/util/https.py", line 37, in _tester
    if func(arg):
  File "/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc49-opt/20.20.8/sw/lcg/releases/LCG_81f/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by complynx** [comment]
Oh, I thought they have tested in os.stat for basestring...

**Comment by mlassnig** [comment]
Now it doesn't except, but it commits seppuku:

$ ./pilot.py -d -q DESY-HH_TEST -l 300
2017-04-20 16:03:57,127 | INFO     | MainThread | __main__                         | main                             | pilot startup - version 2017-04-04.001
2017-04-20 16:03:57,130 | DEBUG    | MainThread | pilot.util.https                 | https_setup                      | User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)
2017-04-20 16:03:57,130 | WARNING  | MainThread | pilot.util.https                 | https_setup                      | Python version <2.7.9 lacks SSL contexts -- falling back to curl
2017-04-20 16:03:57,130 | CRITICAL | MainThread | __main__                         | <module>                         | pilot startup did not succeed -- aborting

**Comment by complynx** [comment]
Wow, it needed some return? I thought we agreed on failures to throw things, not to return success (as back as a year ago).

**Comment by mlassnig** [comment]
you are correct. the way https_setup() is called from the main pilot.py should be simplified and the return removed.

**Comment by mlassnig** [comment]
Thanks!

**Pull request merged**
