### PR TITLE
Added use of thread.event.wait

### PR DESCRIPTION
**Pull request by TWAtGH**
Inspired by queue.get(block=True, timeout=1), I replaced the polling of args.graceful_stop.is_set() with args.graceful_stop.wait(timeout=1)

### CODE REVIEW

**Comment by TWAtGH** [comment]
This maybe doesnt work with Python2.6, because the doc says that the thread.event.wait() methods always returns None.
"Changed in version 2.7: Previously, the method always returned None."
2.6 support required?

**Comment by complynx** [comment]
It is not required, but it is strongly recommended right now.
I'm not the fan of 2.6 and I develop without it's support in mind, but if some feature was introduced for example in 2.7.9, rather than previous builds, we may lack it. See pilot.util.https

**Comment by mlassnig** [comment]
Hi, python 2.6 is required as long as we have grid nodes running on SLC6, which is unfortunately a majority still. Upgrade to CC7 (with Py27 default) is underway though so hopefully by the end of the year we can remove any Py26 dependencies. For now unfortunately it's mandatory, sorry.

**Comment by TWAtGH** [comment]
Ok good to know. No problem, easy to fix. Will do it tomorrow.

**Comment by mlassnig** [comment]
Let's keep this open for now. The whole event/thread/process handling needs some more discussion.

**Pull request closed without merging**
